//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace genturfahi.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("genturfahi.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   lojiban script: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContentLabel {
            get {
                return ResourceManager.GetString("ContentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About genturfa&apos;i に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CopyrightItem {
            get {
                return ResourceManager.GetString("CopyrightItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnglishItem {
            get {
                return ResourceManager.GetString("EnglishItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FileItem {
            get {
                return ResourceManager.GetString("FileItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HelloWorld! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string HelpItem {
            get {
                return ResourceManager.GetString("HelpItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Japanese に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string JapaneseItem {
            get {
                return ResourceManager.GetString("JapaneseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language(_L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LanguagesItem {
            get {
                return ResourceManager.GetString("LanguagesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open(_O) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string OpenItem {
            get {
                return ResourceManager.GetString("OpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parse に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParseButtonLabel {
            get {
                return ResourceManager.GetString("ParseButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   parse result: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ParseResultLabel {
            get {
                return ResourceManager.GetString("ParseResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   parse result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ResultFieldDescription {
            get {
                return ResourceManager.GetString("ResultFieldDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save As(_A) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveAsItem {
            get {
                return ResourceManager.GetString("SaveAsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SaveItem {
            get {
                return ResourceManager.GetString("SaveItem", resourceCulture);
            }
        }
    }
}
